print("Hello World!")
#print("Hello Again")
#print("I like typing like this")
#print("This is fun.")
#print("Yay! Printing.")
#print("I'd much rather 'not'.")
#print('I "said" do not touch this.')
#print("My name is Willie Rose")